# Generated by Django 2.2 on 2020-08-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncparameter',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='syncparameter',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
