# Generated by Django 2.2.13 on 2020-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20200826_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncparameter',
            name='value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
