# Generated by Django 2.2.13 on 2020-08-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20200827_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Sync')),
            ],
        ),
    ]
