# Generated by Django 2.2.13 on 2020-08-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20200828_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialparameter',
            name='value',
            field=models.TextField(max_length=2000),
        ),
    ]
