# Generated by Django 2.2.13 on 2020-08-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20200828_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialparameter',
            name='value',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='syncparameter',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
