# Generated by Django 2.2.13 on 2020-08-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20200828_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synchistory',
            old_name='error',
            new_name='message',
        ),
    ]
