# Generated by Django 2.2.13 on 2020-08-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20200831_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synchistory',
            old_name='date_time',
            new_name='end_time',
        ),
    ]
