# Generated by Django 2.2.13 on 2020-08-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_synchistory_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchistory',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
