# Generated by Django 2.2.13 on 2020-08-31 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20200831_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchistory',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
