# Generated by Django 2.2.13 on 2020-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_sync_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sync',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Running')], default='0', max_length=1, null=True),
        ),
    ]
