# Generated by Django 2.2.13 on 2020-09-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20200901_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sync',
            name='last_run',
        ),
    ]
