# Generated by Django 2.2.13 on 2020-09-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_remove_sync_last_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synchistory',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
