# Generated by Django 2.2.13 on 2020-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20200901_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync',
            name='cron_expression',
            field=models.TextField(blank=True, null=True),
        ),
    ]
