# Generated by Django 2.2.13 on 2020-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_auto_20200901_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="Can find your expression in <a href='https://crontab.guru/examples.html' target='_blank'>Crontab Guru</a>.", max_length=255, null=True),
        ),
    ]
