# Generated by Django 2.2.13 on 2020-09-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20200901_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialparameter',
            name='key',
            field=models.CharField(choices=[('host', 'Host'), ('server', 'Server'), ('instance', 'Instance'), ('user', 'User'), ('password', 'Password'), ('driver', 'Driver'), ('port', 'Port'), ('database', 'Database'), ('controller', 'Controller')], default=('host', 'Host'), max_length=20),
        ),
    ]
