# Generated by Django 2.2.13 on 2020-09-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20200902_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncparameter',
            name='_type',
            field=models.CharField(choices=[('python', 'Python'), ('json', 'JSON')], default='python', max_length=20, verbose_name='Type'),
        ),
    ]
