# Generated by Django 2.2.13 on 2020-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_syncparameter__type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='application',
            field=models.CharField(choices=[('nettime6', 'NetTime 6'), ('manager', 'SPEC Manager'), ('visma', 'Visma RH'), ('exactian', 'Exactian')], default=('nettime6', 'NetTime 6'), max_length=20),
        ),
        migrations.AlterField(
            model_name='sync',
            name='synchronize',
            field=models.CharField(choices=[('employees', 'Employees'), ('structure', 'Structure')], default=('employees', 'Employees'), max_length=20),
        ),
    ]
