# Generated by Django 2.2.13 on 2020-09-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_auto_20200924_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('reduce', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('requirements', models.CharField(blank=True, max_length=100, null=True)),
                ('expression', models.TextField(blank=True, help_text='Create method to apply to a json structure.', null=True)),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.Sync')),
            ],
        ),
    ]
