# Generated by Django 2.2.13 on 2020-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_syncprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncprocess',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='syncprocess',
            name='requirements',
        ),
        migrations.AddField(
            model_name='syncprocess',
            name='_help',
            field=models.CharField(blank=True, help_text='About the procedure.', max_length=200, null=True, verbose_name='Help'),
        ),
        migrations.AlterField(
            model_name='syncprocess',
            name='expression',
            field=models.TextField(blank=True, help_text='Procedure that can process the origin response "origin_response".', null=True),
        ),
        migrations.AlterField(
            model_name='syncprocess',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
