# Generated by Django 2.2.13 on 2020-09-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_remove_syncprocess_reduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncprocess',
            name='requirements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='syncprocess',
            name='expression',
            field=models.TextField(blank=True, help_text='Procedure that can process the origin response             "origin_response".', null=True),
        ),
    ]
