# Generated by Django 2.2.13 on 2020-11-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_auto_20200929_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync',
            name='synchronize',
            field=models.CharField(choices=[('employees', 'Employees'), ('structure', 'Structure'), ('results', 'Results')], default=('employees', 'Employees'), max_length=20),
        ),
    ]
