# Generated by Django 2.2.13 on 2021-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_auto_20201109_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncprocess',
            name='expression',
            field=models.TextField(blank=True, help_text='Procedure that can process the "origin_response".', null=True),
        ),
    ]
