# Generated by Django 2.2.13 on 2021-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_auto_20201109_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Running'), ('2', 'Queued')], default='0', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='syncprocess',
            name='expression',
            field=models.TextField(blank=True, help_text='Procedure that can process the "origin_response".', null=True),
        ),
    ]
