# Generated by Django 2.2.13 on 2021-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_auto_20210304_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='application',
            field=models.CharField(choices=[('nettime6', 'NetTime 6'), ('manager', 'SPEC Manager DB'), ('manager_api', 'SPEC Manager API'), ('visma', 'Visma RH'), ('exactian', 'Exactian')], default=('nettime6', 'NetTime 6'), max_length=20),
        ),
    ]
